/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotAMemberRouteImport } from './routes/not-a-member'
import { Route as IplIndexRouteImport } from './routes/ipl/index'
import { Route as IplLaporanRouteImport } from './routes/ipl/laporan'
import { Route as IplPengeluaranRouteImport } from './routes/ipl/pengeluaran'
import { Route as IplVerifikasiRouteImport } from './routes/ipl/verifikasi'
import { Route as ProblemsIndexRouteImport } from './routes/problems/index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems/$problemId'
import { Route as ProblemsNewRouteImport } from './routes/problems/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAMemberRoute = NotAMemberRouteImport.update({
  id: '/not-a-member',
  path: '/not-a-member',
  getParentRoute: () => rootRouteImport,
} as any)
const IplIndexRoute = IplIndexRouteImport.update({
  id: '/ipl/',
  path: '/ipl/',
  getParentRoute: () => rootRouteImport,
} as any)
const IplLaporanRoute = IplLaporanRouteImport.update({
  id: '/ipl/laporan',
  path: '/ipl/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const IplPengeluaranRoute = IplPengeluaranRouteImport.update({
  id: '/ipl/pengeluaran',
  path: '/ipl/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const IplVerifikasiRoute = IplVerifikasiRouteImport.update({
  id: '/ipl/verifikasi',
  path: '/ipl/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsNewRoute = ProblemsNewRouteImport.update({
  id: '/problems/new',
  path: '/problems/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-a-member': typeof NotAMemberRoute
  '/ipl/laporan': typeof IplLaporanRoute
  '/ipl/pengeluaran': typeof IplPengeluaranRoute
  '/ipl/verifikasi': typeof IplVerifikasiRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/new': typeof ProblemsNewRoute
  '/ipl/': typeof IplIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-a-member': typeof NotAMemberRoute
  '/ipl/laporan': typeof IplLaporanRoute
  '/ipl/pengeluaran': typeof IplPengeluaranRoute
  '/ipl/verifikasi': typeof IplVerifikasiRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/new': typeof ProblemsNewRoute
  '/ipl': typeof IplIndexRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-a-member': typeof NotAMemberRoute
  '/ipl/laporan': typeof IplLaporanRoute
  '/ipl/pengeluaran': typeof IplPengeluaranRoute
  '/ipl/verifikasi': typeof IplVerifikasiRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/new': typeof ProblemsNewRoute
  '/ipl/': typeof IplIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-a-member'
    | '/ipl/laporan'
    | '/ipl/pengeluaran'
    | '/ipl/verifikasi'
    | '/problems/$problemId'
    | '/problems/new'
    | '/ipl/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-a-member'
    | '/ipl/laporan'
    | '/ipl/pengeluaran'
    | '/ipl/verifikasi'
    | '/problems/$problemId'
    | '/problems/new'
    | '/ipl'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/not-a-member'
    | '/ipl/laporan'
    | '/ipl/pengeluaran'
    | '/ipl/verifikasi'
    | '/problems/$problemId'
    | '/problems/new'
    | '/ipl/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotAMemberRoute: typeof NotAMemberRoute
  IplLaporanRoute: typeof IplLaporanRoute
  IplPengeluaranRoute: typeof IplPengeluaranRoute
  IplVerifikasiRoute: typeof IplVerifikasiRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  ProblemsNewRoute: typeof ProblemsNewRoute
  IplIndexRoute: typeof IplIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-a-member': {
      id: '/not-a-member'
      path: '/not-a-member'
      fullPath: '/not-a-member'
      preLoaderRoute: typeof NotAMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl/': {
      id: '/ipl/'
      path: '/ipl'
      fullPath: '/ipl/'
      preLoaderRoute: typeof IplIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl/laporan': {
      id: '/ipl/laporan'
      path: '/ipl/laporan'
      fullPath: '/ipl/laporan'
      preLoaderRoute: typeof IplLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl/pengeluaran': {
      id: '/ipl/pengeluaran'
      path: '/ipl/pengeluaran'
      fullPath: '/ipl/pengeluaran'
      preLoaderRoute: typeof IplPengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl/verifikasi': {
      id: '/ipl/verifikasi'
      path: '/ipl/verifikasi'
      fullPath: '/ipl/verifikasi'
      preLoaderRoute: typeof IplVerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/new': {
      id: '/problems/new'
      path: '/problems/new'
      fullPath: '/problems/new'
      preLoaderRoute: typeof ProblemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotAMemberRoute: NotAMemberRoute,
  IplLaporanRoute: IplLaporanRoute,
  IplPengeluaranRoute: IplPengeluaranRoute,
  IplVerifikasiRoute: IplVerifikasiRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  ProblemsNewRoute: ProblemsNewRoute,
  IplIndexRoute: IplIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
